### ISSUE TITLE
Akses ke aplikasi lewat Github Pages

### ISSUE THREAD

**Issue by diorahman** [BlankOn/Peta#3]
Referensi: https://help.github.com/articles/creating-project-pages-manually/

Letakan index.html dan semua aset terkait di cabang tersebut, sehingga aplikasi dapat dinikmati di https://blankon.github.io/peta (atau jika nanti ada CNAME yang bersesuaian kita bisa buat, misalnya: https://peta.blankon.id)

Sukses!

**Comment by diorahman** [comment]
cc, Pak @mdamt

**Comment by winluxhuman** [comment]
Sudah saya buat pak cabang gh-pages di BlankOn/peta. silakan dicoba di http://blankon.github.io/peta/
![screenshot from 2015-06-07 16-32-39](https://cloud.githubusercontent.com/assets/6603217/8023358/a22e1764-0d33-11e5-8461-5f78ae3eea6f.png)
