### ISSUE TITLE
Menggunakan esri.leaflet

### ISSUE THREAD

**Issue by diorahman** [BlankOn/Peta#4]
Terjadi perubahan `rootUrl` ke layanan `rest` milik BIG.

Silakan lihat contoh: https://github.com/data-blankon-id/api-wms-tiles/blob/gh-pages/index.html

Url untuk laman utama masih tetap: https://data-blankon-id.github.io/api-wms-tiles/

cc. @mdamt

**Comment by winluxhuman** [comment]
oke pak, sedang ditangani. omong-omong apakah servernya sedang maintenis pak?

**Comment by winluxhuman** [comment]
sudah saya perbaharui di repo pribadi, tetapi masih bingung untuk fork ke organisasi

**Comment by winluxhuman** [comment]
sudah saya push ke BlankOn Peta
![screenshot from 2015-06-07 16-32-39](https://cloud.githubusercontent.com/assets/6603217/8023343/e70e0e4e-0d32-11e5-95f8-215d93fd7366.png)
